package co.com.bancolombia.kstreamprocessor.dto;


import com.fasterxml.jackson.annotation.JsonProperty;

public record BasicData(TextType INFA_SEQUENCE, TextType INFA_OP_TYPE, TextType infa_operation_owner,
                        TextType infa_operation_time, TextType infa_operation_type,
                        TextType INFA_TABLE_NAME, TextType infa_transaction_id,
                        TextType CD_ACTIVIDAD_ECONOMICA, boolean CD_ACTIVIDAD_ECONOMICA_Present,
                        String CD_CALIFICACION_INTERNA, boolean CD_CALIFICACION_INTERNA_Present,
                        String CD_CARGO_U_OFICIO, boolean CD_CARGO_U_OFICIO_Present,
                        TextType CD_CIIU, boolean CD_CIIU_Present, TextType CD_CIUDAD_EXPEDICION,
                        boolean CD_CIUDAD_EXPEDICION_Present, TextType CD_CIUDAD_NACIMIENTO,
                        boolean CD_CIUDAD_NACIMIENTO_Present, String CD_CLASE_DE_GRUPO,
                        boolean CD_CLASE_DE_GRUPO_Present, TextType CD_CONSULTA_DE_EXTRACTOS,
                        boolean CD_CONSULTA_DE_EXTRACTOS_Present, TextType CD_DEPARTAMENTO_EXPEDICION,
                        boolean CD_DEPARTAMENTO_EXPEDICION_Present, String CD_DEPARTAMENTO_NACIMIENTO,
                        boolean CD_DEPARTAMENTO_NACIMIENTO_Present, String CD_ENTIDAD_ESTATAL,
                        boolean CD_ENTIDAD_ESTATAL_Present, String CD_ENTIDAD_ESTATAL_DESCENT,
                        boolean CD_ENTIDAD_ESTATAL_DESCENT_Present, TextType CD_ESTADO_CIVIL,
                        boolean CD_ESTADO_CIVIL_Present, String CD_ESTADO_CLIENTE,
                        boolean CD_ESTADO_CLIENTE_Present, String CD_ESTADO_DOCUMENTO,
                        boolean CD_ESTADO_DOCUMENTO_Present, TextType CD_ESTADO_VINCULACION,
                        boolean CD_ESTADO_VINCULACION_Present, String CD_ESTRATO,
                        boolean CD_ESTRATO_Present, TextType CD_GENERO, boolean CD_GENERO_Present,
                        String CD_INCAPAZ, boolean CD_INCAPAZ_Present, TextType CD_MEDIO_ACTUALIZACION,
                        boolean CD_MEDIO_ACTUALIZACION_Present, String CD_NATURALEZA_ENTIDAD,
                        boolean CD_NATURALEZA_ENTIDAD_Present, String CD_NIVEL_ACADEMICO,
                        boolean CD_NIVEL_ACADEMICO_Present, String CD_OCUPACION,
                        boolean CD_OCUPACION_Present, TextType CD_PAIS_EXPEDICION,
                        boolean CD_PAIS_EXPEDICION_Present, TextType CD_PAIS_NACIMIENTO,
                        boolean CD_PAIS_NACIMIENTO_Present, TextType CD_PROFESION,
                        boolean CD_PROFESION_Present, String CD_RELACIONAMIENTO,
                        boolean CD_RELACIONAMIENTO_Present, String CD_REPORTE_COSTOS_TOTALES,
                        boolean CD_REPORTE_COSTOS_TOTALES_Present, TextType CD_ROL_DE_NEGOCIO,
                        boolean CD_ROL_DE_NEGOCIO_Present, TextType CD_SECTOR,
                        boolean CD_SECTOR_Present, String CD_SEGMENTACION_SARLAFT,
                        boolean CD_SEGMENTACION_SARLAFT_Present, TextType CD_SEGMENTO,
                        boolean CD_SEGMENTO_Present, String CD_SOCIEDAD_COMERC_O_CIVIL,
                        boolean CD_SOCIEDAD_COMERC_O_CIVIL_Present, TextType CD_SUB_CIIU,
                        boolean CD_SUB_CIIU_Present, TextType CD_SUBSECTOR,
                        boolean CD_SUBSECTOR_Present, TextType CD_SUBSEGMENTO,
                        boolean CD_SUBSEGMENTO_Present, String CD_TIPO_CONTRATO,
                        boolean CD_TIPO_CONTRATO_Present, TextType CD_TIPO_DOCUMENTO,
                        boolean CD_TIPO_DOCUMENTO_Present, String CD_TIPO_ENTIDAD,
                        boolean CD_TIPO_ENTIDAD_Present, TextType CD_TIPO_INTERLOCUTOR_COMER,
                        boolean CD_TIPO_INTERLOCUTOR_COMER_Present, TextType CD_TIPO_RELACIONADO,
                        boolean CD_TIPO_RELACIONADO_Present, String CD_TIPO_VIVIENDA,
                        boolean CD_TIPO_VIVIENDA_Present, TextType CD_TRATAMIENTO,
                        boolean CD_TRATAMIENTO_Present, String CODIGO_SISBEN,
                        boolean CODIGO_SISBEN_Present, NumberType CONSOLIDATION_IND,
                        boolean CONSOLIDATION_IND_Present, String EMPRESA_DONDE_LABORA,
                        boolean EMPRESA_DONDE_LABORA_Present, TextType FECHA_ACTUALIZACION,
                        boolean FECHA_ACTUALIZACION_Present, TextType FECHA_CLIENTE_DESDE,
                        boolean FECHA_CLIENTE_DESDE_Present, String FECHA_CLIENTE_HASTA,
                        boolean FECHA_CLIENTE_HASTA_Present, TextType FECHA_EXPEDICION,
                        boolean FECHA_EXPEDICION_Present, String FECHA_INGRESO,
                        boolean FECHA_INGRESO_Present, TextType FECHA_NACIMIENTO,
                        boolean FECHA_NACIMIENTO_Present, TextType FECHA_VENCIMIENTO,
                        boolean FECHA_VENCIMIENTO_Present, String FECHA_VINCULACION,
                        boolean FECHA_VINCULACION_Present, TextType FL_AUT_RECIBIR_EXT_PDF,
                        boolean FL_AUT_RECIBIR_EXT_PDF_Present, TextType FL_EMPLEADO,
                        boolean FL_EMPLEADO_Present, String FL_EMPRESA_LIQUIDADA,
                        boolean FL_EMPRESA_LIQUIDADA_Present, String FL_FALLECIDO,
                        boolean FL_FALLECIDO_Present, String FL_LEY_INTERVENCION,
                        boolean FL_LEY_INTERVENCION_Present, TextType FL_NO_AUT_COMPARTIR_INFORM,
                        boolean FL_NO_AUT_COMPARTIR_INFORM_Present, TextType FL_NO_AUT_ENVIO_CORREOS,
                        boolean FL_NO_AUT_ENVIO_CORREOS_Present, TextType FL_NO_AUT_ENVIO_MSJ_TEXTO,
                        boolean FL_NO_AUT_ENVIO_MSJ_TEXTO_Present, TextType FL_NO_AUT_RECIBIR_OFERTAS,
                        boolean FL_NO_AUT_RECIBIR_OFERTAS_Present, TextType FL_PEP_COLOMBIA,
                        boolean FL_PEP_COLOMBIA_Present, String FL_PERSONA_BLOQUEADA,
                        boolean FL_PERSONA_BLOQUEADA_Present, String FL_PERSONA_NO_OBJETIVO_COM,
                        boolean FL_PERSONA_NO_OBJETIVO_COM_Present, TextType FL_REALIZA_OPE_MONEDA_EXT,
                        boolean FL_REALIZA_OPE_MONEDA_EXT_Present, String FL_SECUESTRADO,
                        boolean FL_SECUESTRADO_Present, String FL_TESORERIA,
                        boolean FL_TESORERIA_Present, NumberType HUB_STATE_IND,
                        boolean HUB_STATE_IND_Present, TextType NOMBRE_CORTO_O_SIGLA,
                        boolean NOMBRE_CORTO_O_SIGLA_Present, TextType NOMBRE_O_RAZON,
                        boolean NOMBRE_O_RAZON_Present, NumberType NUMERO_DE_HIJOS,
                        boolean NUMERO_DE_HIJOS_Present, TextType NUMERO_DOCUMENTO,
                        boolean NUMERO_DOCUMENTO_Present, TextType NUMERO_DOCUMENTO_EXTERNO,
                        boolean NUMERO_DOCUMENTO_EXTERNO_Present, TextType PERSONAS_A_CARGO,
                        boolean PERSONAS_A_CARGO_Present, TextType PRIMER_APELLIDO,
                        boolean PRIMER_APELLIDO_Present, TextType PRIMER_NOMBRE,
                        boolean PRIMER_NOMBRE_Present, String REGISTRO_DESPLAZADO,
                        boolean REGISTRO_DESPLAZADO_Present, TextType ROWID_OBJECT,
                        boolean ROWID_OBJECT_Present, TextType SEGUNDO_APELLIDO,
                        boolean SEGUNDO_APELLIDO_Present, TextType SEGUNDO_NOMBRE,
                        boolean SEGUNDO_NOMBRE_Present, TextType TAMANO_COMERCIAL,
                        boolean TAMANO_COMERCIAL_Present

                        ){

    public record TextType(String string){}
    public record NumberType(@JsonProperty("long") int myLong){}


}

