server:
  port: 8080
spring:
  application:
    name: "ProjectClient"
  kafka:
    bootstrap:
      servers: "localhost:9092,localhost:9093,localhost:9094"
    topic:
      test-in: "topic_0"
      test-in-1: "topic_1"
    security:
      protocol: "PLAINTEXT"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
commons:
  jms:
    input-concurrency: 10
    input-queue: "DEV.QUEUE.2"
    input-queue-alias: ""
    reactive: true
    output-concurrency: 10
    output-queue: "DEV.QUEUE.1"
    producer-ttl: 0
ibm:
  mq:
    conn-name: "127.0.0.1(1414)"
    channel: "DEV.APP.SVRCONN"
    user: "app"
    password: "passw0rd"
plain-text-pattern:
  config:
    files: "C:\\Users\\jespinosa\\Desktop\\proyectoClientes\\applications\\app-service\\src\\main\\resources\\pattern-config"
adapter:
  peq:
    url: "https://clientes-int-qa.apps.ambientesbc.com/clientes-integracion-qa/equivalences/peq"
    #url: "${PEQ-URL:https://eqadapt-api-comercio-exterior-integracion.apps.ocpdes.ambientesbc.lab}"
    timeout: 5000
    cache:
      expireAfter: 3600
    header:
      originApplication: "MDM-SINCRO_CLIENTES_KAFKA"
      destinationApplication: "CIF-SINCRO_CLIENTES_KAFKA"
      originSociety: "1000"
      targetSociety: "1000"